project_id = "hbdxzwmicykcmjsgoadt"

[functions.resource-download]
verify_jwt = false

[functions.get-available-slots]
verify_jwt = false

[functions.view-booking]
verify_jwt = false

[functions.gatewayapi-webhook]
verify_jwt = false



